from pathlib import Path

def build_markdown_report(records):
    """Terima list of dict (nim,nama,hadir,akhir,predikat) → string Markdown tabel."""
    lines = [
        "# Rekap Nilai Mahasiswa",
        "",
        "| NIM | Nama | Hadir (%) | Nilai Akhir | Predikat |",
        "|---|---|---:|---:|:---:|",
    ]
    for r in records:
        lines.append(
            "| {nim} | {nama} | {hadir:.2f} | {akhir:.2f} | {pred} |".format(
                nim=r['nim'], nama=r['nama'], hadir=r['hadir'], akhir=r['akhir'], pred=r['predikat']
            )
        )
    lines.append("")
    lines.append("Generated by Kiki Mahesta Ganteng(Eka Rizki Suwarno ehe)")
    return "\n".join(lines)

def save_text(path, content):
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(content, encoding="utf-8")


def build_html_report(records):
    """
    Bangun laporan HTML modern & responsif dengan pewarnaan predikat (A–E).
    Tidak mengubah data/angka; hanya tampilan.
    """
    # mapping kelas warna
    predikat_class = {
        "A": "predikat-A",
        "B": "predikat-B",
        "C": "predikat-C",
        "D": "predikat-D",
        "E": "predikat-E",
    }

    # --- CSS modern + dark-mode ---
    style = """
    <style>
      :root{
        --bg: #f5f7fa;
        --card: #ffffff;
        --text: #2d3748;
        --muted:#718096;
        --thead:#2b6cb0;
        --theadText:#ffffff;
        --rowEven:#f9fbfd;
        --rowHover:#eaf4ff;
        --ring: rgba(66,153,225,0.35);

        --A:#a8e6a1; /* hijau muda */
        --B:#bfe3ff; /* biru muda */
        --C:#fff7a3; /* kuning */
        --D:#ffc4b0; /* oranye */
        --E:#ffb3b3; /* merah muda */
      }
      @media (prefers-color-scheme: dark){
        :root{
          --bg:#0f172a;
          --card:#0b1220;
          --text:#e2e8f0;
          --muted:#94a3b8;
          --thead:#1e3a8a;
          --theadText:#e2e8f0;
          --rowEven:#0e1628;
          --rowHover:#0f213f;
          --ring: rgba(96,165,250,0.35);

          --A:#14532d; --B:#0b3a5c; --C:#3d2f00; --D:#4a1f16; --E:#4a0f0f;
        }
      }

      * { box-sizing: border-box; }
      body{
        margin:0; padding:24px;
        background:var(--bg); color:var(--text);
        font: 15px/1.5 system-ui, -apple-system, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", "Apple Color Emoji","Segoe UI Emoji";
      }
      .container{
        max-width: 1100px; margin: 0 auto;
      }
      .header{
        text-align:center; margin-bottom:16px;
      }
      .title{
        margin:0 0 6px; letter-spacing:.5px; text-transform:uppercase;
      }
      .subtitle{
        margin:0; color:var(--muted); font-size:13px;
      }
      .card{
        background:var(--card);
        border-radius:14px;
        box-shadow: 0 4px 18px rgba(0,0,0,.10);
        overflow:hidden;
        border:1px solid rgba(0,0,0,.04);
      }
      .table-wrap{
        width:100%;
        overflow:auto;
      }
      table{
        border-collapse: collapse;
        width:100%;
        min-width:760px;
      }
      thead th{
        position: sticky; top:0; z-index:1;
        background:var(--thead); color:var(--theadText);
        text-transform:uppercase; font-weight:700; font-size:12px;
        letter-spacing:.6px; padding:12px 14px; text-align:center;
      }
      tbody td{
        padding:12px 14px; border-bottom:1px solid rgba(0,0,0,.06);
        text-align:center; vertical-align:middle;
      }
      tbody tr:nth-child(even){ background: var(--rowEven); }
      tbody tr:hover{ background: var(--rowHover); transition: background .15s ease-in; }

      /* kolom angka rata kanan */
      td.col-hadir, td.col-akhir { text-align:right; font-variant-numeric: tabular-nums; }

      /* badge predikat */
      .badge{
        display:inline-block; min-width:38px;
        padding:4px 10px; border-radius:999px; font-weight:700;
        box-shadow: inset 0 0 0 1px rgba(0,0,0,.06);
      }
      .predikat-A .badge{ background: var(--A); }
      .predikat-B .badge{ background: var(--B); }
      .predikat-C .badge{ background: var(--C); }
      .predikat-D .badge{ background: var(--D); }
      .predikat-E .badge{ background: var(--E); }

      /* kolom NIM rata kiri agar mudah discan */
      td.col-nim, td.col-nama{ text-align:left; }

      .footer{
        font-size:12px; color:var(--muted); text-align:center; margin-top:14px;
      }

      /* fokus saat tab scroll */
      .table-wrap:focus-visible{
        outline: 3px solid var(--ring);
        border-radius: 10px;
      }
    </style>
    """

    # --- HTML skeleton ---
    head = f"""
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <title>Rekap Nilai</title>
      {style}
    </head>
    """

    # build rows
    rows = []
    for r in records:
        cls = predikat_class.get(str(r.get("predikat","")).upper(), "")
        rows.append(
            "<tr class='{cls}'>"
            "<td class='col-nim'>{nim}</td>"
            "<td class='col-nama'>{nama}</td>"
            "<td class='col-hadir'>{hadir:.2f}</td>"
            "<td class='col-akhir'>{akhir:.2f}</td>"
            "<td><span class='badge'>{pred}</span></td>"
            "</tr>".format(
                cls=cls,
                nim=r["nim"],
                nama=r["nama"],
                hadir=float(r["hadir"]),
                akhir=float(r["akhir"]),
                pred=r["predikat"],
            )
        )

    body = f"""
    <body>
      <div class="container">
        <header class="header">
          <h2 class="title">Rekap Nilai Mahasiswa</h2>
          <p class="subtitle">Universtas Duta Bangsa Surakarta</p>
        </header>

        <section class="card">
          <div class="table-wrap" tabindex="0" aria-label="Tabel rekap nilai dapat discroll">
            <table>
              <thead>
                <tr>
                  <th>NIM</th>
                  <th>Nama</th>
                  <th>Hadir (%)</th>
                  <th>Nilai Akhir</th>
                  <th>Predikat</th>
                </tr>
              </thead>
              <tbody>
                {''.join(rows)}
              </tbody>
            </table>
          </div>
        </section>

        <p class="footer">Generated by student_performance_tracker</p>
      </div>
    </body>
    """

    return "<html>" + head + body + "</html>"


def save_html(path, content):
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(content, encoding="utf-8")
