"""Pembangun laporan Markdown + helper simpan teks."""

from pathlib import Path

def build_markdown_report(records):
    """Terima list of dict (nim,nama,hadir,akhir,predikat) → string Markdown tabel."""
    lines = [
        "# Rekap Nilai Mahasiswa",
        "",
        "| NIM | Nama | Hadir (%) | Nilai Akhir | Predikat |",
        "|---|---|---:|---:|:---:|",
    ]
    for r in records:
        lines.append(
            "| {nim} | {nama} | {hadir:.2f} | {akhir:.2f} | {pred} |".format(
                nim=r['nim'], nama=r['nama'], hadir=r['hadir'], akhir=r['akhir'], pred=r['predikat']
            )
        )
    lines.append("")
    lines.append("Generated by student_performance_tracker")
    return "\n".join(lines)

def save_text(path, content):
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(content, encoding="utf-8")

def build_html_report(records):
    """Bangun laporan HTML berwarna berdasarkan predikat."""
    warna = {
        "A": "#a3f7a3",  # hijau muda
        "B": "#a3d8f7",  # biru muda
        "C": "#fff6a3",  # kuning
        "D": "#f7c6a3",  # oranye
        "E": "#f7a3a3",  # merah muda
    }
    html = [
        "<html><head><meta charset='utf-8'><title>Rekap Nilai</title></head><body>",
        "<h2>Rekap Nilai Mahasiswa</h2>",
        "<table border='1' cellspacing='0' cellpadding='6'>",
        "<tr><th>NIM</th><th>Nama</th><th>Hadir (%)</th><th>Nilai Akhir</th><th>Predikat</th></tr>"
    ]
    for r in records:
        c = warna.get(r['predikat'], "#fff")
        html.append(
            f"<tr style='background-color:{c}'><td>{r['nim']}</td><td>{r['nama']}</td>"
            f"<td align='right'>{r['hadir']:.2f}</td><td align='right'>{r['akhir']:.2f}</td>"
            f"<td align='center'>{r['predikat']}</td></tr>"
        )
    html.append("</table><p>Generated by student_performance_tracker</p></body></html>")
    return "\n".join(html)

def save_html(path, content):
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(content, encoding="utf-8")
